# Generated by Django 2.2 on 2020-01-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpassword',
            field=models.CharField(default='tops', max_length=200),
            preserve_default=False,
        ),
    ]
