# Generated by Django 2.2 on 2020-02-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(choices=[('Sports', 'Sports'), ('Concerts', 'Concerts'), ('Political', 'Political')], max_length=100)),
                ('event_name', models.CharField(max_length=200)),
                ('event_desc', models.TextField()),
                ('event_price', models.CharField(max_length=200)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
